<template>
  <div>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
    <p>Switch</p>
  </div>
</template>

<script>
  export default {
    name: 'SwitchDemo'
  }
</script>

<style lang="scss" scoped>

</style>